### ISSUE TITLE
unix is not a valid dgram protocol

### ISSUE THREAD

**Issue by jhnlsn** [winstonjs/winston-syslog#17]
{protocol: 'unix'} is invalid for

```
new dgram.Socket(this.protocol);
```

as outlined in the documentation for node v0.10.20

http://nodejs.org/api/dgram.html#dgram_dgram_createsocket_type_callback

**Comment by santigimeno** [comment]
@jhnlsn as explained here: https://github.com/winstonjs/winston-syslog/issues/16#issuecomment-26485757 `unix-dgram` module is being used
