### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by gdw2** [winstonjs/winston-syslog#23]

**Comment by siavashg** [comment]
We'd love to use this but without understanding the license first we can't.
Thanks

**Comment by tehshane** [comment]
+1 for adding a license

**Comment by santigimeno** [comment]
@indexzero ping

**Comment by indexzero** [comment]
This is MIT. Feel free to add it @santigimeno, attribute yourself too of course :smile_cat:

**Comment by santigimeno** [comment]
https://github.com/winstonjs/winston-syslog/pull/60
