### ISSUE TITLE
TCP messages are being written to a single line in syslog

### ISSUE THREAD

**Issue by brakon** [winstonjs/winston-syslog#47]
When you log multiple messages and have it setup to use TCP when syslog outputs it is in the same line.

To work around this issue we had to add a "\n" to the end of the message so syslog treats it as a separate log message.
e.g:
```
info('test 1');
info('test 2');
```

Will show up in syslog as:
```
2015-06-16T15:27:47-06:00 xxxxxxx xxxxxx[11917]: info: test1<174>Jun 16 15:27:47 xxxxxxxx xxxxxx[11917]: info: test2
```

**Comment by brakon** [comment]
Other transports like Console, etc append a new line ("\n") to the message before sending, should I do a pull request for this?

**Comment by brakon** [comment]
any update?

**Comment by arabold** [comment]
Ran into the same problem today. This pretty much makes it impossible to use syslog output for something like Logstash which relies on new lines at the end of messages. I'll checkout your pull request. Thanks!

**Comment by santigimeno** [comment]
I guess this can be closed as https://github.com/winstonjs/winston-syslog/pull/48 was merged
