### ISSUE TITLE
Fails install without build-essential g++

### ISSUE THREAD

**Issue by binarymist** [winstonjs/winston-syslog#49]
npm install winston-syslog --save
-
> unix-dgram@0.2.1 install /myProj/node_modules/winston-syslog/node_modules/unix-dgram
> node-gyp rebuild

make: Entering directory `/myProj/node_modules/winston-syslog/node_modules/unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
make: g++: Command not found
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 127
make: Leaving directory `/myProj/node_modules/winston-syslog/node_modules/unix-dgram/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /myProj/node_modules/winston-syslog/node_modules/unix-dgram
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! unix-dgram@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unix-dgram@0.2.1 install script.
npm ERR! This is most likely a problem with the unix-dgram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls unix-dgram
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "winston-syslog" "--save"
npm ERR! cwd /myProj
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Needed sudo apt-get install build-essential g++ in order to install node module.

**Comment by indexzero** [comment]
This is not a bug, but I'll leave it open to document the additional platform needs. You will need these packages on most binary node modules though.

**Comment by binarymist** [comment]
Yeah, may be worth adding to the readme or wiki? Then it's "known".

**Comment by santigimeno** [comment]
As of `1.2.0` `unix-dgram` is an `optionalDependenvy` so `g++` should not be mandatory.
