### ISSUE TITLE
Unnecessary mandatory option.localhost

### ISSUE THREAD

**Issue by md2k** [winstonjs/winston-syslog#55]
Hi all, i think that option in Subj should not be a mandatory because local syslog daemon already will set hostname if you send to /dev/log unix domain. if you send messages to remote server it also can determinate name of server by it's ip or log just IP, but since `localhost` option is mandatory Syslog message is misconfigured, because it have additional tag into syslog event. Maybe for many of users it is not a problem, but i found it not handy because i should : 
1. Maintain copy of plugin myself
2. i should write additional parsers to catch what i want from malformed syslog event.

i think it is best to have possibility to set option.localhost to `false or null` to skip this tag in a syslog event.

**Comment by santigimeno** [comment]
@md2k seems a sensible change. Would you create a PR for this?

**Comment by santigimeno** [comment]
@md2k Can you take a look at https://github.com/winstonjs/winston-syslog/pull/58 and see if it works for you?

**Comment by md2k** [comment]
Hi @santigimeno  i'll try it over weekends , thanks.

**Comment by santigimeno** [comment]
@md2k did you get to test it? Thanks!

**Comment by md2k** [comment]
Pardon, didn't had any chance to find time for that. but still in my to-do list

**Comment by santigimeno** [comment]
@md2k no problem, I just don't want to delay a new release to much and wanted to add this functionality. Just let me know when you test it. Thanks!

**Comment by md2k** [comment]
@santigimeno  i think do not late with release, we can add this functionality later. from code prespective it should work fine (patch above), but currently busy with other important tasks so kept logging with my own patch which mostly looks same as yours.

**Comment by santigimeno** [comment]
Merged: https://github.com/winstonjs/winston-syslog/commit/e8f0a7217fe8623d62b60aee74e1363dcc8941ba
It'll be available in version `1.2.0`
