### ISSUE TITLE
Closing socket connection

### ISSUE THREAD

**Issue by yagop** [winstonjs/winston-syslog#61]
Any way to close the socket connection?

Its possible to open a new connection and closing it every message is delivered?

**Comment by santigimeno** [comment]
2015-12-21 16:37 GMT+01:00 Yago <notifications@github.com>:

> Any way to close the socket connection?
>
Yes, you should be able to call `close` on the transport or `remove` the
transport from `winston`.

> Its possible to open a new connection and closing it every message is
> delivered?
>
A simple way would be to create a wrapper that adds the transport before
logging and removes it afterwards.

**Comment by santigimeno** [comment]
There's a problem at the moment though. For this to work correctly you need the code from current master AND replace `Syslog` with `syslog` here: https://github.com/winstonjs/winston-syslog/blob/master/lib/winston-syslog.js#L111

**Comment by yagop** [comment]
Thanks a lot.
