### ISSUE TITLE
Options for Type of Syslog Protocol

### ISSUE THREAD

**Issue by tacticurv** [winstonjs/winston-syslog#69]
The documentation and the comments in code mention that the library is compliant with RFC 3164 and RFC 5424. The default value for type in options is 'BSD' which corresponds to RFC 3164 Protocol. What is the value for options.type corresponding to RFC 5424.

**Comment by faust64** [comment]
I think you're just looking for `5424' (see https://github.com/winstonjs/winston-syslog/blob/master/test/format-test.js#L78)

**Comment by datnordstrom** [comment]
Can we put this in the documentation?

**Comment by faust64** [comment]
In all fairness, this option is only used as an argument loading glossy (https://github.com/winstonjs/winston-syslog/blob/master/lib/winston-syslog.js#L87), and they don't seem to document it either.

https://github.com/squeeks/glossy/blob/master/lib/glossy/produce.js
I haven't checked, although it sounds like you could enable 5424 compliance setting your type to `foobar`.

Anyway, not having write access to this repository, the best I can do is submit a PR: winstonjs/winston-syslog#79

**Comment by santigimeno** [comment]
https://github.com/squeeks/glossy/blob/master/lib/glossy/produce.js
I haven't checked, although it sounds like you could enable 5424 compliance setting your type to foobar.

@faust64 yeah, it looks like 5424 is the default for glossy

**Comment by santigimeno** [comment]
Fixed by https://github.com/winstonjs/winston-syslog/commit/785d15b9d45d11dc554edad1aa84b35ed7ff9e02. Thanks
