### ISSUE TITLE
app_name is being ignored and replaced by process title

### ISSUE THREAD

**Issue by adematte** [winstonjs/winston-syslog#73]
Since 1.2.2 the option app_name does not work anymore and is being replaced by process title. We are reverting to 1.2.1 for now. 

our code snippet to reproduce the error
```js
var winston = require('winston');
var os = require('os');
require('winston-syslog').Syslog;
var logger = new(winston.Logger)({
    transports: [
        new winston.transports.Syslog({
            host: 'someHost',
            protocol: 'udp4',
            localhost: os.hostname(),
            app_name: 'thisWillBeIgnored'
        })
    ]
});
```

**Comment by faust64** [comment]
funny to find that issue, I just noticed the same thing myself, ....
I think the following would address our issue: winstonjs/winston-syslog/pull/74
