### ISSUE TITLE
TCP4 is no longer a valid protocol option

### ISSUE THREAD

**Issue by sudhanne** [winstonjs/winston-syslog#78]
This broke as part of the 1.2.4 release.  "tcp4" is no longer a valid protocol option.

**Comment by hshixun** [comment]
use tcp instead

**Comment by santigimeno** [comment]
@sudhanne you're right, I supposed that no-one was using protocol names that were meaningless for the `node.js` API. So I just decided to support: `tcp`, `udp4`, `udp6`, `unix` and `unix-connect`. I was wrong. In fact, I just saw that `tcp4` is an acceptable protocol value in the `README`. I'll revert the commits for now. These changes, if we think are good, should have gone in, in a major version. Sorry for the trouble.

**Comment by santigimeno** [comment]
Fixed in `v1.2.5`. Thanks
