### ISSUE TITLE
Update unix-dgram version in dependencies for fix build on Solaris

### ISSUE THREAD

**Issue by usebaz** [winstonjs/winston-syslog#83]
Update `unix-dgram` version to `v2.0.1` or upper. For fix build on Solaris.
PR in `unix-dgram`: https://github.com/bnoordhuis/node-unix-dgram/pull/46

Promised by @santigimeno 
Thanks!

**Comment by santigimeno** [comment]
@usebaz sorry for still not updating the module. It's on my radar and have made some progress but have little time these days.
