### ISSUE TITLE
OSX: Nothing seems to get logged (Console app)

### ISSUE THREAD

**Issue by arthurakay** [winstonjs/winston-syslog#90]
I recently posted this question to [StackOverflow](https://stackoverflow.com/questions/47873193/nodejs-logging-winston-out-to-syslog-on-osx) but I am hoping for a faster response here.

In short I don't see anything logged into the Console app on OSX.

```
const winston = require('winston');
require('winston-syslog').Syslog; // eslint-disable-line

const env = process.env.NODE_ENV;
let syslogConfig = {
    "host": "localhost",
    "port": 514,
    "protocol": "unix",
    "path": "/var/run/syslog"
};

const logger = new winston.Logger({
    levels: winston.config.syslog.levels,
    colors: winston.config.syslog.colors
});

logger.add(winston.transports.Syslog, syslogConfig);

logger.add(winston.transports.Console, {
    json: false,
    colorize: true,
    timestamp: true
});

// this should be logged and visible from Console app...
logger.error('Hello, world!');

module.exports = logger;
```

Are my configuration settings somehow incorrect? I get no errors in my terminal.

* Node v6.9.1
* NPM v5.4.2
* winston v2.4.0
* winston-syslog v2.0.0
* OSX v10.12.6 (Sierra)

**Comment by santigimeno** [comment]
Haven't tried your code yet but can you try with `winston-syslog@1.2.6`? Thanks

**Comment by arthurakay** [comment]
I just tried with `1.2.6`... same result (nothing displayed in Console app).

**Comment by santigimeno** [comment]
I tried your code on Linux and works correctly (logs both in syslog and console). I don't have access to an OS X right now but will test in the following days.

**Comment by arthurakay** [comment]
Ok, thank you!

Yes it does output my log to the terminal (iTerm 2), it just never shows up in Console.

**Comment by arthurakay** [comment]
Upon further investigation, I do see that my message gets output to syslog in OSX... but I'm still *very* confused about things.

I only see the messages output by my node `console.error()` call when I tail `syslog` itself:

    syslog -w

I still don't see the messages logged in the Console app (remember, OSX Sierra is supposed to use "unified logging") so I have no idea what's going on there.

Perhaps I just horribly misunderstand what `syslog` does? In any case, I'll close this.
